unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g mouse on
set -g default-terminal "tmux-256color"

set -g prefix C-s

bind | split-window -h
bind - split-window -v

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Settings for Catppuccin
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# Set the theme to Catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-position top
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialise TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
